# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Deep-Learning',
                'doc_host': 'https://nextrick.github.io',
                'git_url': 'https://github.com/nextrick/Deep-Learning',
                'lib_path': 'Deep_Learning'},
  'syms': {'Deep_Learning.core': {'Deep_Learning.core.foo': ('core.html#foo', 'Deep_Learning/core.py')}}}
